import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/layout";
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/toast";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Toaster />
        <main className="relative">
          <Navbar />
          <div className="">{children}</div>
        </main>
      </body>
    </html>
  );
}
